### ISSUE TITLE
Change font-size

### ISSUE THREAD

**Issue by S1SYPHOS** [JonasDoebertin/kirby-visual-markdown#104]
Hey there,
I just found out about this plugin, exactly what my clients needed, thank you so much!
One tiny detail I found annoying though is the font-size of normal-sized text, it's just so tiny! Hotfix for me was this:
```scss
.cm-s-visualmarkdown {
    // font: 1em/1.75 monospace changing into
    font: 1rem/1.75 monospace;
}
```

What do you think?
