### ISSUE TITLE
can't setup tools / toolbar visibility

### ISSUE THREAD

**Issue by damienfaivre** [JonasDoebertin/kirby-visual-markdown#108]
Hi, 

I wanted to clean some of my visual markdown fields from unnecessary tools, but it looks like I can't as I got an error `strtolower() expects parameter 1 to be string, array given`.

It occurs with tools list and toolbar option. Here is my blueprint : 

```
intro:
    label: Intro
    type: markdown
        toolbar: hide
    width: 1/2
    required: required
```

Am I doing something wrong ? Is it a known error ? I'm on kirby 2.5.5, didn't try on an older version yet.

Thanks in advance guys !

**Comment by MathiasGmeiner** [comment]
Looks like you formatted the line "toolbar" wrong, try this one:

```
intro:
  label: Intro
  type: markdown
  toolbar: hide
  width: 1/2
  required: required
```
